# coding: utf-8

"""
    Data Repository Service

     GET request: Fetch a DrsObject from the database by sending a unique ID through the request  POST request: Create a non-existing DrsObject in the database by giving an identifier  DELETE request: Delete a DrsObject from the database by unique identifier  PUT request: Update an existing DrsObject by unique identifier and the changes in the body   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: ga4gh-cloud@ga4gh.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import drs_api
from drs_api.api.data_repository_service_api import DataRepositoryServiceApi  # noqa: E501
from drs_api.rest import ApiException


class TestDataRepositoryServiceApi(unittest.TestCase):
    """DataRepositoryServiceApi unit test stubs"""

    def setUp(self):
        self.api = DataRepositoryServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_object_ga4gh_drs_v1_objects_object_id_delete(self):
        """Test case for delete_object_ga4gh_drs_v1_objects_object_id_delete

        Delete a DrsObject  # noqa: E501
        """
        pass

    def test_get_health_ga4gh_drs_v1_health_get(self):
        """Test case for get_health_ga4gh_drs_v1_health_get

        Check if the API is running correctly  # noqa: E501
        """
        pass

    def test_get_object_alias_ga4gh_drs_v1_objects_get(self):
        """Test case for get_object_alias_ga4gh_drs_v1_objects_get

        Query DrsObjects on alias  # noqa: E501
        """
        pass

    def test_get_object_ga4gh_drs_v1_objects_object_id_access_access_id_get(self):
        """Test case for get_object_ga4gh_drs_v1_objects_object_id_access_access_id_get

        Get a URL for fetching bytes  # noqa: E501
        """
        pass

    def test_get_object_ga4gh_drs_v1_objects_object_id_get(self):
        """Test case for get_object_ga4gh_drs_v1_objects_object_id_get

        Retrieve a DrsObject  # noqa: E501
        """
        pass

    def test_post_object_ga4gh_drs_v1_objects_post(self):
        """Test case for post_object_ga4gh_drs_v1_objects_post

        Create a new DrsObject  # noqa: E501
        """
        pass

    def test_put_object_ga4gh_drs_v1_objects_object_id_put(self):
        """Test case for put_object_ga4gh_drs_v1_objects_object_id_put

        Update a DrsObject  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
