# coding: utf-8

"""
    Data Repository Service

     GET request: Fetch a DrsObject from the database by sending a unique ID through the request  POST request: Create a non-existing DrsObject in the database by giving an identifier  DELETE request: Delete a DrsObject from the database by unique identifier  PUT request: Update an existing DrsObject by unique identifier and the changes in the body   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: ga4gh-cloud@ga4gh.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import drs_api
from drs_api.api.user_management_api import UserManagementApi  # noqa: E501
from drs_api.rest import ApiException


class TestUserManagementApi(unittest.TestCase):
    """UserManagementApi unit test stubs"""

    def setUp(self):
        self.api = UserManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user_users_username_delete(self):
        """Test case for delete_user_users_username_delete

        Delete a user  # noqa: E501
        """
        pass

    def test_delete_user_users_username_get(self):
        """Test case for delete_user_users_username_get

        Get user info  # noqa: E501
        """
        pass

    def test_post_user_users_post(self):
        """Test case for post_user_users_post

        Create a new user  # noqa: E501
        """
        pass

    def test_put_user_users_username_put(self):
        """Test case for put_user_users_username_put

        Update a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
