# coding: utf-8

# flake8: noqa

"""
    Data Repository Service

     GET request:  - Fetch a DrsObject from the database by sending a unique ID through the request - Fetch an access url to the data which the object refers to - Fetch DrsObjects by doing a search on the aliases  POST request:  - Create a non-existing DrsObject in the database by giving an identifier  DELETE request:  - Delete a DrsObject from the database by unique identifier  PUT request:  - Update an existing DrsObject by unique identifier and the changes in the body   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: ict@cmgg.be
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from drs_api.api.data_repository_service_api import DataRepositoryServiceApi
from drs_api.api.health_api import HealthApi
from drs_api.api.login_api import LoginApi
# import ApiClient
from drs_api.api_client import ApiClient
from drs_api.configuration import Configuration
# import models into sdk package
from drs_api.models.access_methods import AccessMethods
from drs_api.models.access_url import AccessURL
from drs_api.models.all_of_drs_object_access_methods import AllOfDrsObjectAccessMethods
from drs_api.models.all_of_drs_object_checksums import AllOfDrsObjectChecksums
from drs_api.models.all_of_drs_object_contents import AllOfDrsObjectContents
from drs_api.models.basic_response import BasicResponse
from drs_api.models.body_login_token_post import BodyLoginTokenPost
from drs_api.models.checksums import Checksums
from drs_api.models.contents_expanded import ContentsExpanded
from drs_api.models.drs_object import DrsObject
from drs_api.models.error import Error
from drs_api.models.http_validation_error import HTTPValidationError
from drs_api.models.token import Token
from drs_api.models.validation_error import ValidationError
